/**
 *
 * $Id$
 */
package eu.kalafatic.explorer.model.explorer.validation;

import eu.kalafatic.explorer.model.explorer.EDeviceType;
import eu.kalafatic.explorer.model.explorer.IntegerToPortMapEntry;
import eu.kalafatic.explorer.model.explorer.Port;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link eu.kalafatic.explorer.model.explorer.Device}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeviceValidator {
	boolean validate();

	boolean validateIp(String value);
	boolean validateHost(String value);
	boolean validateMask(String value);
	boolean validateInterfaces(EList<Object> value);
	boolean validateType(EDeviceType value);
	boolean validatePort(Port value);
	boolean validateOpenPorts(EMap<Integer, Port> value);

	boolean validateOpenPorts(EList<IntegerToPortMapEntry> value);

	boolean validateOpenPorts(IntegerToPortMapEntry value);
}
