/**
 *
 * $Id$
 */
package eu.kalafatic.explorer.model.explorer.validation;

import eu.kalafatic.explorer.model.explorer.Port;

/**
 * A sample validator interface for {@link eu.kalafatic.explorer.model.explorer.IntegerToPortMapEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntegerToPortMapEntryValidator {
	boolean validate();

	boolean validateTypedKey(Integer value);

	boolean validateTypedValue(Port value);

	boolean validateKey(Integer value);
	boolean validateValue(Port value);
}
