/**
 *
 * $Id$
 */
package eu.kalafatic.explorer.model.explorer.validation;

import eu.kalafatic.explorer.model.explorer.Node;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link eu.kalafatic.explorer.model.explorer.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateParent(Node value);
	boolean validateChildren(EMap<String, Node> value);
}
