/**
 *
 * $Id$
 */
package eu.kalafatic.explorer.model.explorer.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.explorer.model.explorer.Route}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RouteValidator {
	boolean validate();

	boolean validateNetTarget(String value);
	boolean validateGateway(String value);
	boolean validateInterface(String value);
	boolean validateMetrics(int value);
}
